csis_eam_homepage:
    pattern:  /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: vitrine
        permanent: true

CSISEamBundle_admin:
    resource: "@CSISEamBundle/Controller/AdminController.php"
    type:     annotation

CSISEamBundle_category:
    resource: "@CSISEamBundle/Controller/CategoryController.php"
    type:     annotation

CSISEamBundle_equipment:
    resource: "@CSISEamBundle/Controller/EquipmentController.php"
    type:     annotation

CSISEamBundle_institution:
    resource: "@CSISEamBundle/Controller/InstitutionController.php"
    type:     annotation

CSISEamBundle_laboratory:
    resource: "@CSISEamBundle/Controller/LaboratoryController.php"
    type:     annotation

CSISEamBundle_people:
    resource: "@CSISEamBundle/Resources/config/routing/people.yml"
    prefix:   /peoples

CSISEamBundle_tag:
    resource: "@CSISEamBundle/Resources/config/routing/tag.yml"
    prefix:   /tags

CSISEamBundle_vitrine:
    resource: "@CSISEamBundle/Resources/config/routing/vitrine.yml"
    prefix:   /vitrine

CSISEamBundle_supersearch:
    resource: "@CSISEamBundle/Resources/config/routing/supersearch.yml"
    prefix:   /search



