services:
    csis.type.user_selector:
        class: CSIS\EamBundle\Form\Type\UserSelectorType
        arguments:
            - @doctrine.orm.default_entity_manager
            - @session
            - @router
        tags:
            - { name: form.type, alias: csis_user_selector }
            
    csis.type.tag_selector:
        class: CSIS\EamBundle\Form\Type\TagSelectorType
        arguments:
            - @doctrine.orm.default_entity_manager
            - @session
            - @event_dispatcher
            - @security.context
        tags:
            - { name: form.type, alias: csis_tags_selector }
    
    csis.type.laboratory_selector:
        class: CSIS\EamBundle\Form\Type\LaboratorySelectorType
        arguments: 
            - "@doctrine.orm.entity_manager"
            - "@security.context"
        tags:
            - { name: form.type, alias: csis_laboratory_selector }

    csis.type.institution_selector:
        class: CSIS\EamBundle\Form\Type\InstitutionSelectorType
        arguments: 
            - "@doctrine.orm.entity_manager"
            - "@security.context"
        tags:
            - { name: form.type, alias: csis_institution_selector }

    csis.twig.csis_extension:
        class: CSIS\EamBundle\Twig\TwigFilters
        tags:
            - { name: twig.extension }

    csis.form.type.custom_equipment_tag_collection:
      class: CSIS\EamBundle\Form\CustomEquipmentTagCollectionType
      tags:
        - { name: form.type, alias: custom_equipment_tag_collection }

    csis.listener.tag:
        class:      CSIS\EamBundle\Listener\TagListener
        arguments:
            - @swiftmailer.mailer
            - @router
            - @twig
            - @doctrine.orm.default_entity_manager
            - %tag%
        tags:
            - { name: kernel.event_subscriber }
