<?php

namespace CSIS\EamBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EquipmentTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipmentTagRepository extends EntityRepository
{
}
