<?php

namespace CSIS\EamBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\Query\ResultSetMapping;

use CSIS\UserBundle\Entity\User;

/**
 * LaboratoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LaboratoryRepository extends EntityRepository {
    
    /*
     * used by laboratory index
     */
    public function findByOwnerOrderByAcronym(User $user) {
        $qb = $this->createQueryBuilder('l');
        $qb = $this->qbByOwners($qb, $user);
        $qb = $this->qbReachByUser($qb, $user);
        $qb = $this->qbOrderByAcronym($qb);

        return $qb->getQuery()->getResult();
    }
    
    /*
     * used by admin index
     */
    public function findByOwnersOrderByEditDate(User $user) {
        $qb = $this->createQueryBuilder('l');
        $qb = $this->qbByOwners($qb, $user);
        $qb = $this->qbOderByEditDate($qb);

        return $qb->getQuery()->getResult();
    }
    
    /*
     * used by user index
     */
    public function findByOwners(User $user) {
      $qb = $this->createQueryBuilder('l');
      $qb = $this->qbByOwners($qb, $user);
      
      return $qb->getQuery()->getResult();
    }
    
    public function getQbReachableLaboratoriesOrderedByAcronym(User $user)
    {
        $qb = $this->createQueryBuilder('l');
        $qb = $this->qbOrderByAcronym($qb);
        $qb = $this->qbReachByUser($qb, $user);

        return $this->qbByOwners($qb, $user);
    }
    
    public function getQbByOwnersOrderByAcronym(User $user) {
        $qb = $this->createQueryBuilder('l');
        $qb = $this->qbOrderByAcronym($qb);
        
        return $this->qbByOwners($qb, $user);
    }
    
    private function qbReachByUser(QueryBuilder $qb, User $user) {
        if ($user->hasRole('ROLE_GEST_ESTAB') || $user->hasRole('ROLE_ADMIN')) {
            return $qb;
        }

        return $qb
            ->orWhere($qb->expr()->eq('l', ':laboratory'))
            ->orWhere($qb->expr()->eq('l.institution', ':institution'))
            ->setParameter('institution', $user->getInstitution())
            ->setParameter('laboratory', $user->getLab());
    }

    private function qbByOwners(QueryBuilder $qb, User $user) {
        if ($user->hasRole('ROLE_GEST_ESTAB') || $user->hasRole('ROLE_ADMIN')) {
            return $qb;
        }

        return $qb
            ->leftJoin('l.institution', 'i')
            ->orWhere(':user MEMBER OF l.owners')
            ->orWhere(':user MEMBER OF i.owners')
            ->setParameter('user', $user);
    }

    private function qbOderByEditDate(QueryBuilder $qb) {
        return $qb->orderBy('l.lastEditDate', 'DESC');
    }
    
    private function qbOrderByAcronym(QueryBuilder $qb) {
        return $qb->orderBy('l.acronym', 'ASC');
    }

    /**
     * @param Laboratory $laboratory
     *
     * @return bool
     */
    public function isInstitutionUsed(Institution $institution)
    {
        $qb = $this->createQueryBuilder('l')
            ->select('count(l)')
            ->where('l.institution = :institution')
            ->setParameter('institution', $institution);

        return $qb->getQuery()->getSingleScalarResult() > 0;
    }
}
