csis_user:
    resource: "@CSISUserBundle/Resources/config/routing.yml"
    prefix:   /

csis_eam:
    resource: "@CSISEamBundle/Resources/config/routing.yml"
    prefix:   /

# Vendor
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_console:
    resource: "@CoreSphereConsoleBundle/Resources/config/routing.yml"
    prefix: /console
