jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_GEST_USER:      ROLE_USER
        ROLE_GEST_TAGS:      ROLE_USER
        ROLE_GEST_EQUIP:     [ROLE_USER]
        ROLE_GEST_LAB:       [ROLE_GEST_EQUIP]
        ROLE_GEST_ESTAB:     ROLE_GEST_LAB
        ROLE_ADMIN:          [ROLE_ALLOWED_TO_SWITCH, ROLE_GEST_ESTAB, ROLE_GEST_LAB, ROLE_GEST_EQUIP, ROLE_GEST_TAGS, ROLE_GEST_USER, ROLE_GEST_PEOPLE, ROLE_USER]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        # Firewall principal pour le reste de notre site
        main:
            pattern: ^/                      # ^/ = tout ce qui commence par / = tout notre site
            form_login:                      # On définit notre méthode d'authentification
                provider:    fos_userbundle  # On lit l'authentification au provider définit plus haut
                remember_me: true            # On active la possibilité du "Se souvenir de moi" (désactivé par défaut)
                csrf_provider: form.csrf_provider
                default_target_path: /admin
            remember_me:
                key:         %secret%        # On définit la clé pour le remember_me (%secret% est un parametre de parameters.ini)
            anonymous:       true            # On autorise les utilisateurs anonymes (non identifiés)
            logout:          true            # On autorise la déconnexion manuelle (désactivé par défaut)
            switch_user: true
            

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register/confirmed, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_GEST_USER }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_USER }
