equipment:
    pattern:  /
    defaults: { _controller: CSISEamBundle:Equipment:index }
    requirements:
        _method: get
        page: \d+

equipment_new:
    pattern:  /new
    defaults: { _controller: CSISEamBundle:Equipment:new }
    requirements:
        _method: get

equipment_create:
    pattern:  /
    defaults: { _controller: CSISEamBundle:Equipment:create }
    requirements: 
        _method: post

equipment_show:
    pattern:  /{id}
    defaults: { _controller: CSISEamBundle:Equipment:show }
    requirements:
        _method: get
        id: \d+

equipment_edit:
    pattern:  /{id}/edit
    defaults: { _controller: CSISEamBundle:Equipment:edit }
    requirements:
        _method: get
        id: \d+

equipment_edit_tags:
    pattern:  /{id}/edit/tags
    defaults: { _controller: CSISEamBundle:Equipment:editTags }
    requirements:
        _method: get
        id: \d+

equipment_fetch_tags:
    pattern:  /{id}/edit/tags/fetch
    defaults: { _controller: CSISEamBundle:Equipment:fetchTags }
    requirements:
        _method: get
        id: \d+

equipment_fetch_relative_tags:
    pattern:  /{id}/edit/tags/relatives
    defaults: { _controller: CSISEamBundle:Equipment:fetchRelativeTags }
    requirements:
        _method: get
        id: \d+

equipment_update_tags:
    pattern:  /{id}/edit/tags/update
    defaults: { _controller: CSISEamBundle:Equipment:updateTags }
    requirements:
        _method: post
        id: \d+

equipment_update:
    pattern:  /{id}/update
    defaults: { _controller: CSISEamBundle:Equipment:update }
    requirements: 
        _method: post
        id: \d+

equipment_ask_delete:
    pattern:  /{id}/ask_delete
    defaults: { _controller: CSISEamBundle:Equipment:askDelete }
    requirements:
        id: \d+

equipment_delete:
    pattern:  /{id}/delete
    defaults: { _controller: CSISEamBundle:Equipment:delete }
    requirements:
        _method: get
        id: \d+

equipment_credentials:
    pattern:  /{id}/credentials
    defaults: { _controller: CSISEamBundle:Equipment:credentials }
    requirements:
        _method: get
        id: \d+

equipment_credentials_add:
    pattern: /{id}/credentials
    defaults: { _controller: CSISEamBundle:Equipment:credentialsAdd }
    requirements:
        _method: post
        id: \d+ 

equipment_credentials_remove:
    pattern: /{id}/credentials/{owner}/remove
    defaults: { _controller: CSISEamBundle:Equipment:credentialsRemove }
    requirements:
        _method: get
        id: \d+
        owner: \d+

equipment_relatives_tag:
    pattern:  /relativeTags
    defaults: { _controller: CSISEamBundle:Equipment:relativeTags, _format: json }
    requirements:
        _method: post
