people:
    pattern:  /{page}
    defaults: { _controller: "CSISEamBundle:People:index", page: 1 }
    requirements:
        page: \d+

people_show:
    pattern:  /{id}/show
    defaults: { _controller: "CSISEamBundle:People:show" }

people_new:
    pattern:  /new
    defaults: { _controller: "CSISEamBundle:People:new" }

people_create:
    pattern:  /create
    defaults: { _controller: "CSISEamBundle:People:create" }
    requirements: { _method: post }

people_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CSISEamBundle:People:edit" }

people_update:
    pattern:  /{id}/update
    defaults: { _controller: "CSISEamBundle:People:update" }
    requirements: { _method: post }

people_ask_delete:
    pattern:  /{id}/ask_delete
    defaults: { _controller: "CSISEamBundle:People:askDelete" }

people_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CSISEamBundle:People:delete" }

people_create_useraccount:
    pattern:  /{id}/create_useraccount
    defaults: { _controller: "CSISEamBundle:People:createUserAccount" }
