csis_user_index:
    pattern:  /users/list/{page}
    defaults: { _controller: CSISUserBundle:User:Index, page:1 }


user_autocomplete:
    pattern:  /users/autocomplete
    defaults: { _controller: "CSISUserBundle:User:autocomplete", _format: json }
    requirements:
        _method: post

csis_user_edit:
    pattern:  /users/{id}/edit
    defaults: { _controller: CSISUserBundle:User:Edit }
    requirements:
        id: \d+
  
csis_user_show:
    pattern:  /users/{id}
    defaults: { _controller: CSISUserBundle:User:Show }
    requirements:
        id: \d+
    
csis_user_delete:
    pattern:  /users/{id}/delete
    defaults: { _controller: CSISUserBundle:User:Delete }
    requirements:
        id: \d+

csis_user_edit_lab:
    pattern: /users/{id}/editLab
    defaults: { _controller: CSISUserBundle:User:editLaboratoryDependance }
    requirements:
        id: \d+

csis_user_edit_institution:
    pattern: /users/{id}/editInstitution
    defaults: { _controller: CSISUserBundle:User:editInstitutionDependance }

csis_user_add_lab:
    pattern: /register/addLab
    defaults: { _controller: CSISUserBundle:Registration:addLaboratoryDependance }

csis_user_add_institution:
    pattern: /register/addInstitution
    defaults: { _controller: CSISUserBundle:Registration:addInstitutionDependance }

